apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
images:
- name: 248239598373.dkr.ecr.ap-northeast-2.amazonaws.com/thingsflos-hands-on
  newName: 248239598373.dkr.ecr.ap-northeast-2.amazonaws.com/thingsflos-hands-on
  newTag: 9c06f0ee
resources:
- ../base
patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- service-patch.yaml
