apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
images:
- name: nginx
  newName: nginx
  newTag: latest
resources:
- ../base
patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- service-patch.yaml
